# Assignment For Numpy

### Difficulty Level Beginner

#### 1. Import the numpy package under the name np

In [2]:
import numpy as np

#### 2. Create a null vector of size 10

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Create a vector with values ranging from 10 to 49

In [6]:
arr=np.array(range(10,49))

#### 4. Find the shape of previous array in question 3

In [7]:
arr.shape

(39,)

#### 5. Print the type of the previous array in question 3

In [9]:
type(arr)

numpy.ndarray

#### 6. Print the numpy version and the configuration

In [ ]:
print(np.__version__)
print(np.show_config())

#### 7. Print the dimension of the array in question 3

In [15]:
arr.ndim

1

#### 8. Create a boolean array with all the True values

In [24]:
np.full(5,fill_value=True,dtype=bool)

array([ True,  True,  True,  True,  True])

#### 9. Create a two dimensional array

In [27]:
a2d=np.arange(10).reshape(2,5)
a2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 10. Create a three dimensional array

In [34]:
a3d=np.arange(12).reshape(2,2,3)
a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Difficulty Level Easy

#### 11. Reverse a vector (first element becomes last)

In [42]:
a3d=a3d[::-1]
a3d

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  1,  2],
        [ 3,  4,  5]]])

#### 12. Create a null vector of size 10 but the fifth value which is 1

In [46]:
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 13. Create a 3x3 identity matrix

In [47]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 14. arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

#### 15. arr1 = np.array([[1., 2., 3.],

####                                   [4., 5., 6.]])  

#### arr2 = np.array([[0., 4., 1.],

####                             [7., 2., 12.]])
#### Multiply arr1 with arr2

In [50]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

#### 16. arr1 = np.array([[1., 2., 3.],

####            [4., 5., 6.]]) 

#### arr2 = np.array([[0., 4., 1.],

####            [7., 2., 12.]])
#### Make an array by comparing both the arrays provided above

In [52]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
res_arr = arr1 > arr2
res_arr

array([[ True, False,  True],
       [False,  True, False]])

#### 17. Extract all odd numbers from arr with values(0-9)

In [77]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

#### 18. Replace all odd numbers to -1 from previous array

In [79]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 19. arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [80]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

#### 20. Create a 2d array with 1 on the border and 0 inside

In [92]:
a2d = np.ones(25).reshape(5,5).astype(int)
a2d[1:4,1:4]=0
a2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Difficulty Level Medium

#### 21. arr2d = np.array([[1, 2, 3],

####            [4, 5, 6], 

####            [7, 8, 9]])
Replace the value 5 to 12

In [93]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

#### 22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [94]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64 #Confusion not sure i.e 1 array pointing to what either [1,2,3] or whole [[1,2,3],[4,5,6]] i select 1 option
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### 23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [98]:
arr2d = np.arange(10).reshape(2,5)
arr2d[:1] # or arr2d[0]

array([[0, 1, 2, 3, 4]])

#### 24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [102]:
arr2d = np.arange(10).reshape(2,5)
arr2d[1:,1:2] #or arr2d[1][1]

array([[6]])

#### 25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [103]:
arr2d = np.arange(10).reshape(2,5)
arr2d[:,2:3]

array([[2],
       [7]])

#### 26. Create a 10x10 array with random values and find the minimum and maximum values

In [112]:
arr2d = np.random.random((10,10))
arr2d.max(),arr2d.min()

(0.9943317664901412, 0.003351128197526698)

#### 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [125]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b) #set(a) & set(b) through this common items can be done

{2, 4}

#### 28. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [132]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.searchsorted(a,np.intersect1d(a,b))

array([1, 5], dtype=int64)

#### 29. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [140]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.67911971,  1.6448074 , -0.81462782,  0.26268318],
       [-2.6018704 , -0.18222626,  0.78224561,  0.18743483],
       [-0.85742097, -2.26648573, -1.41676528, -0.14888728],
       [ 1.43768204, -0.62346813,  1.23566207,  1.73318558],
       [ 0.78662906,  0.29065224, -1.83649433,  0.48196608]])

#### 30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [191]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
(data[names!='Will'] & data[names!='Joe'])

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Difficulty Level Hard

#### 31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [192]:
a2d = np.arange(15).reshape(5,3)
a2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### 32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [195]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

#### 33. Swap axes of the array you created in Question 32

In [201]:
np.swapaxes(arr,0,1),np.swapaxes(arr,0,2)

(array([[[ 0,  1,  2,  3],
         [ 8,  9, 10, 11]],
 
        [[ 4,  5,  6,  7],
         [12, 13, 14, 15]]]),
 array([[[ 0,  8],
         [ 4, 12]],
 
        [[ 1,  9],
         [ 5, 13]],
 
        [[ 2, 10],
         [ 6, 14]],
 
        [[ 3, 11],
         [ 7, 15]]]))

#### 34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [203]:
arr = np.arange(10)
arr=np.sqrt(arr)
arr[arr==0.5]=0
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#### 35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [211]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
max_arr=np.maximum(arr1,arr2)
max_arr

array([ 0.36051773,  0.73285215,  0.5154229 ,  0.40365165,  1.34359916,
        1.11647324, -0.5589439 ,  0.83696799,  0.60984655,  0.06428553,
        1.38473047,  1.64295482])

#### 36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [220]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted(np.unique(names)) # infact unique function perform unique values as well as asc sorting

['Bob', 'Joe', 'Will']

#### 37. a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [236]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b) # this will first find unique value of a means that are not present in b then assign to a 
a

array([1, 2, 3, 4])

#### 38. Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [244]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
sampleArray[:,1]=10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

#### 39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [246]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### 40. Generate a matrix of 20 random values and find its cumulative sum

In [254]:
m = np.random.randn(20).astype(int)
m.cumsum()

array([ 0,  0,  1,  0, -1, -1,  0,  0,  0,  0, -1,  0,  0,  1,  1,  1,  0,
        0,  1,  1], dtype=int32)